question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "All planets in the Solar System orbit the Sun.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Psychology is the science of behavior and mind.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "A plant that has a life cycle for more than a year is known as an annual.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Igneous rocks are formed by excessive heat and pressure.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Salt is 100% composed of Sodium.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "The Earth revolves around the Sun in one year.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Upwelling in the ocean provides colder nutrient rich water for plants and decomposers.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "The Earth and the Moon roughly have the same mass.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "An Astronomical Unit is the distance between Earth and the Moon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "The Sun is considered a star.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "An average human can go two weeks without water.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "Great Whites sometimes perform the bump-and-bite attack (a test bite) on victims.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]
